version: '3'
services:
  api:
    build:
      context: src/api/
    environment:
      - ASPNETCORE_ENVIRONMENT=Container
    ports:
      - "5000:80"
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"